language: objective-c

matrix:
  include:
    - osx_image: xcode11
    - osx_image: xcode10.2

addons:
  homebrew:
    packages:
    - swiftlint

script:
  - swift package generate-xcodeproj
  - swift test
  - swiftlint
