language: objective-c
osx_image: xcode10.2

addons:
  homebrew:
    packages:
    - swiftlint

script:
  - swift package generate-xcodeproj
  - swift test
  - swiftlint

branches:
  only:
  - master
  - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
